server:
  port: 8080
  contextPath: /

datasource:
  url: jdbc:h2:~/certificatesdb;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
  driverClassName: org.h2.Driver
  maxPoolSize: 10
  hibernate:
    hbm2ddl.method: create-drop
    show_sql: true
    format_sql: true
    dialect: org.hibernate.dialect.H2Dialect